// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.github.ericzzh.mattermost-plugin-prune",
    "name": "Prune",
    "description": "This plugin perform some simple data retention work",
    "homepage_url": "https://github.com/ericzzh/mattermost-plugin-prune",
    "support_url": "https://github.com/ericzzh/mattermost-plugin-prune",
    "release_notes_url": "https://github.com/ericzzh/mattermost-plugin-prunereleases/tag/",
    "version": "+",
    "min_server_version": "5.37.0",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "GeneralPeriod",
                "display_name": "General prune period",
                "type": "number",
                "help_text": "",
                "placeholder": "",
                "default": 0
            },
            {
                "key": "TeamPolicy",
                "display_name": "Set specific prune policy for teams",
                "type": "custom",
                "help_text": "Input format: team_name=period",
                "placeholder": "",
                "default": ""
            },
            {
                "key": "ChannelPolicy",
                "display_name": "Set specific prune policy for channel",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": ""
            },
            {
                "key": "UserPolicy",
                "display_name": "Set specific prune policy for users",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": ""
            }
        ]
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
export const pluginId = manifest.id;
